### ISSUE TITLE
Document Missing Template Error: The operation couldn’t be completed

### ISSUE THREAD

**Issue by Zuikyo** [Qusic/TraceUtility#1]
hi,I try to build TraceUtility with Mac OS X 10.10.5 ,Xcode7.0 ,but I got an error:
Error: Error Domain=com.apple.instruments Code=-6 "Document Missing Template Error: The operation couldn’t be completed. (com.apple.instruments error -6.)"
have you ever meet this problem?

**Comment by Qusic** [comment]
Not yet. Was that a valid trace document? Can you open it in Instruments?

**Comment by Zuikyo** [comment]
I just found I use the wrong directory of my trace document……now it run successfully!
I'm trying to find a way to parser the data of an Energy Diagnostics Template  trace,but the methods of XRStreamedPowerRun are totally different.So I decompiled XRPowerInstrument.xrplugin, trying to find something useful.
