### ISSUE TITLE
如何在Mac命令行中使用

### ISSUE THREAD

**Issue by codeskyblue** [Qusic/TraceUtility#10]
我对OC不太熟悉，可否指点下如何命令行解析 trace文件

**Comment by Qusic** [comment]
得按需求写代码，命令行不行

**Comment by codeskyblue** [comment]
对OC不熟悉的人搞不定呀

**Comment by LeepengX** [comment]
就是编译完，然后进入到可执行目录下进行使用。
命令行: TraceUtility  xxx.trace
即可使用
