### ISSUE TITLE
通过原来的方法去不到PFInstrumentList了

### ISSUE THREAD

**Issue by monkeydbobo** [Qusic/TraceUtility#12]
###通过原来的方法去不到PFInstrumentList了
通过下面这种昂视可以去到basicList
PFTInstrumentList *recordInstruments = [trace valueForKey:@"_recordingInstruments"];
PFTInstrumentList *basicInstruments =  [trace valueForKey:@"_basicInstruments"];

**Comment by MonkyQ** [comment]
nice!
