### ISSUE TITLE
怎么获取Displayed Surface中的值

### ISSUE THREAD

**Issue by pixuan** [Qusic/TraceUtility#15]
想要获取Instrument里Displayed Surface里的值，请问如何寻找类似于XRVideoCardRun， XRNetworkingInstrument等的类？

**Comment by Qusic** [comment]
`XRNetworkingInstrument` 这种是 legacy 的。新的 instruments 一般不会有 `XRInstrument` 或者
 `XRRun` 的 subclass。
你主要还是要关注 `XRContext` 的这条路，就像代码里 Time Profiler 的那个例子，数据应该都可以从 `container` 那个变量出发来拿到。
