### ISSUE TITLE
PFTLoadPlugins() - crashed

### ISSUE THREAD

**Issue by noshuai** [Qusic/TraceUtility#16]
在code9上编译并运行时, 执行到PFTLoadPlugins()  会出现crash

CoreData: annotation:  Failed to load optimized model at path '/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Frameworks/InstrumentsPackaging.framework/Versions/A/Resources/XRPackageModel.momd/XRPackageModel 9.0.omo'

**Comment by oschanger** [comment]
同

**Comment by louiseyang** [comment]
+1

**Comment by MarStarck** [comment]
这个不是问题，因为Instruments自己也会报这个警报。

**Comment by noshuai** [comment]
@louiseyang 咋样有什么进展了吗? 你们也在研究iOS的性能测试?

**Comment by MonkyQ** [comment]
我在8.3.1上完美运行，换成9也出现同样问题，即使换成8.3.2也还是会挂，似乎动态库有变化了

**Comment by louiseyang** [comment]
@noshuai https://github.com/Qusic/TraceUtility/issues/17#issuecomment-352387758
按照这个可以跑起来了

**Comment by Qusic** [comment]
crash with xcode 9.2 fixed in https://github.com/Qusic/TraceUtility/commit/98648d9d82940efab8f713c147bbcd1abfc4ce90#diff-0cad19250ae08acbc7488724c19cf9e9R34
