### ISSUE TITLE
如何拿取Time Profiler的Narrative

### ISSUE THREAD

**Issue by MonkyQ** [Qusic/TraceUtility#19]
诸位！我想尝试获取App的冷启动、热启动时间，之前统计了线程时间但是由于启动的线程有不同所以并不十分准确，但在Narrative中看到Initalizing与launched时间，但是解析代码中似乎不能获取到，请问大佬们有什么办法或者思路吗！

**Comment by MarStarck** [comment]
你要解析的是什么版本的trace文件

**Comment by MonkyQ** [comment]
抱歉才看到回复！xcode 8.3版本录制的。Emm...您好，用Alloctions录制了内存的文件，解析拿到的事allocation list的信息，那么就只有申请的内存大小，似乎不能拿到释放的动作。我想重绘出在每秒时间点内存的消耗情况，现在只能不断累加Malloc，数值一直增加。尝试了别的模版也没有拿到可靠信息。请问有办法区分消耗和释放的大小么？或者别的模版可以的吗？谢谢！

**Comment by MonkyQ** [comment]
![2018-01-03 3 33 01](https://user-images.githubusercontent.com/16773712/34512165-7cad9c1e-f09b-11e7-9f43-74cc38d81838.png)
![2018-01-03 3 33 16](https://user-images.githubusercontent.com/16773712/34512166-7e34e77c-f09b-11e7-8e0e-98524c408026.png)
![2018-01-03 3 34 37](https://user-images.githubusercontent.com/16773712/34512183-a361c920-f09b-11e7-95a6-81e111b46cc9.png)
补充～想要重绘出图一的效果，获取到图二数据，按秒累加之后数值并不是想要的，明显小于实际内存。

**Comment by oschanger** [comment]
你这个打印的是堆内存，实际占用的内存是resident size，还包含文件缓存、系统库内存

**Comment by MonkyQ** [comment]
Emm...有办法取到Current Size吗？
