### ISSUE TITLE
PFTLoadPlugins(); crash - initializeApplicationDirectoryName: has not been called yet 

### ISSUE THREAD

**Issue by sergey-plevako-badoo** [Qusic/TraceUtility#2]
I am getting the error on the line `PFTLoadPlugins();`
xCode version Version 7.3 (7D175)
   xcode-select version 2343.
The error I have is:
`2016-04-05 11:27:19.388 TraceUtility[7719:123623] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-10174/DVTFoundation/DeveloperStructure/DVTDeveloperPaths.m:58
Details:  +[DVTDeveloperPaths applicationDirectoryName] was called, but +initializeApplicationDirectoryName: has not been called yet. Your process must initialize the application directory name if you use this class.
Object:   <DVTDeveloperPaths>
Method:   +applicationDirectoryName
Thread:   <NSThread: 0x1036134c0>{number = 1, name = main}
Hints: None
Backtrace:
  0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   +[DVTDeveloperPaths applicationDirectoryName] (in DVTFoundation)
  4   -[DVTDeveloperPaths sourceSpecificationSearchPathForPlatform:] (in DVTFoundation)
  5   +[DVTSourceSpecification searchForAndRegisterAllAvailableSpecifications] (in DVTFoundation)
  6   __PFTLoadPlugins_block_invoke (in InstrumentsPlugIn)
  7   _dispatch_client_callout (in libdispatch.dylib)
  8   dispatch_once_f (in libdispatch.dylib)
  9   PFTLoadPlugins (in InstrumentsPlugIn)
 10   main at /Users/sergeyplevako/Documents/Work/TraceUtility/TraceUtility/main.m:13 (in TraceUtility)
 11   start (in libdyld.dylib)`

Developer's directory is seems to be fine 
`(lldb) po PFTDeveloperDirectory();
/Applications/Xcode.app/Contents/Developer`

**Comment by dcaspi** [comment]
The fix is to initialize the application directory before calling `PFTLoadPlugins()`.

To do so:
(1) Link to `/Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework` (by adding it under the 'Link Binary With Libraries' section).
(2) Call `initializeApplicationDirectoryName` before, in the following manner:
    [DVTDeveloperPaths initializeApplicationDirectoryName:@"../../../../../../../Xcode.app/"];
    // Required. Each instrument is a plugin and we have to load them before we can process their data.
    PFTLoadPlugins();

(Source: http://www.cnblogs.com/hyddd/p/5329608.html)

**Comment by Qusic** [comment]
It seems `[DVTDeveloperPaths initializeApplicationDirectoryName:@"Instruments"]` should be enough, according to Instruments.app itself.
