### ISSUE TITLE
求帮忙看看 Activity Monitor中cpu和内存数据怎么获取

### ISSUE THREAD

**Issue by FuckyouBB** [Qusic/TraceUtility#20]
大神的工程 已经可以运行，不过没有Activity Monitor的获取，看了好几天，在解析出来的数据里 怎么也找不到，感觉这个和Time Profile 很不一样，求帮帮忙呗，十分感谢！

**Comment by MonkyQ** [comment]
if ([instrumentID isEqualToString:@"com.apple.xray.instrument-type.activity.all"]) {
                    TUPrint(@"com.apple.xray.instrument-type.activity.all!!!\n");
                    NSMutableArray *CPUArr = [run valueForKey:@"_data"];
                    for (NSMutableDictionary *map in CPUArr) {
                        NSMutableArray *processArr = map[@"Processes"];
                        NSByteCountFormatter *byteFormatter = [[NSByteCountFormatter alloc]init];
                        byteFormatter.countStyle = NSByteCountFormatterCountStyleBinary;
                        for (NSMutableDictionary *proDict in processArr) {
                            NSString *VirtualSize = [byteFormatter stringForObjectValue:proDict[@"VirtualSize"]];
                            NSString *ResidentSize = [byteFormatter stringForObjectValue:proDict[@"ResidentSize"]];
                            NSString *memoryStr = [NSString stringWithFormat:@"#%@ %@\n", VirtualSize, ResidentSize];
                            NSLog(@"%@",memoryStr);
                        }
                    }
                }

关注下对象的结构用key value方法取属性。以上是Activity Monitor的解析可以拿到相应数据哦。

**Comment by FuckyouBB** [comment]
NSMutableArray *CPUArr = [run valueForKey:@"_data"]; 
这一句就不行了
而且我的id是com.apple.xray.instrument-type.activity没有all

**Comment by FuckyouBB** [comment]
感谢感谢，换成8.3就行了， 9 的结构太奇怪了

**Comment by MonkyQ** [comment]
帮上忙就好~有个问题是这里拿到的并不是按时序点打印的。

**Comment by FuckyouBB** [comment]
有一个开始和结束的时间，数组里就没有时间了，65秒有50个元素，感觉 只能 差不多 当成1秒

**Comment by MonkyQ** [comment]
没看到时间信息...

**Comment by MonkyQ** [comment]
请问下，你在哪里找到的时间？

**Comment by FuckyouBB** [comment]
run数据 里面有个XRRUN 里面有个 startTime 和endTime

**Comment by MonkyQ** [comment]
哦哦，那个是录制线程的运行时间，我用不上。

**Comment by FuckyouBB** [comment]
你是要 每个数据对应的时间戳吗？ 好像没有

**Comment by MonkyQ** [comment]
是的是的～ 这里没有-。-很烦
