### ISSUE TITLE
Xcode 9中会报错：This document was saved by a newer version of Instruments and the file format has significantly changed.  The document will need to be opened by the newer version

### ISSUE THREAD

**Issue by vivianali** [Qusic/TraceUtility#22]
怎么解决呢？

**Comment by Qusic** [comment]
crash with xcode 9.2 fixed in https://github.com/Qusic/TraceUtility/commit/98648d9d82940efab8f713c147bbcd1abfc4ce90#diff-0cad19250ae08acbc7488724c19cf9e9R34
