### ISSUE TITLE
update Xcode 9.2 “callTreeView.backtraceRepository” structure changed

### ISSUE THREAD

**Issue by MonkyQ** [Qusic/TraceUtility#24]
I used Xcode 8.3 all the time.Just switch to the 9.2.
Find callTreeView has changed.Just like this. Need Help~~~
This is Xcode 9.2 screenshot.
![2018-02-25 5 18 00](https://user-images.githubusercontent.com/16773712/36640024-0a1c5d2a-1a53-11e8-8b54-3d61176adaa4.png)
![2018-02-25 5 18 22](https://user-images.githubusercontent.com/16773712/36640028-12bb4e28-1a53-11e8-805b-1928354233a0.png)
This is Xcode 8.3 screenshot.
![1111111](https://user-images.githubusercontent.com/16773712/36640046-4be7c15e-1a53-11e8-994e-f38249c6f68c.png)

How to parse the structure？Anyone know or shall we discuss it？

**Comment by Qusic** [comment]
xcode 9.4的time profiler 修复了
