### ISSUE TITLE
XCode 9.3版本不能运行，作者能否介绍一下每次XCode更新后的修改思路？

### ISSUE THREAD

**Issue by DevQiao** [Qusic/TraceUtility#25]
<img width="1063" alt="screen shot 2018-04-03 at 3 03 41 pm" src="https://user-images.githubusercontent.com/10654788/38234396-5d5a561c-3750-11e8-80f2-4e47eaacdc51.png">
安装了Final Cut Pro之后怎么也受到了影响？

> Invalidoverlay plist for extension com.apple.InternalFiltersXPC (file:///Applications/Final%20Cut%20Pro.app/Contents/PlugIns/InternalFiltersXPC.pluginkit/)

但是Plugin的搜索目录不是已经指定在了/Applications/Xcode.app/Contents/Applications/Instruments.app目录下，Final Cut Pro的Plugin并不在这个目录啊

**Comment by Qusic** [comment]
我的mac是公司的，目前没升级10.13，还不能跑xcode9.3。。没有固定的套路，就是普通的debug。。

**Comment by Qusic** [comment]
虽然不知道为啥会找到final cut pro但是这个log不一定和跑不起来有关系，具体还是看崩溃那发生了啥

**Comment by DevQiao** [comment]
断点调试后，在调用`PFTLoadPlugins();`后随即报错，像是对指定对象发送了无法识别的`selector`，先前版本至少在这里是可以跑过去的，哭哭
<img width="1273" alt="screen shot 2018-04-03 at 3 19 36 pm" src="https://user-images.githubusercontent.com/10654788/38235115-990b5c2c-3752-11e8-8169-59ecba3929d8.png">

**Comment by Qusic** [comment]
`handleIssue:type:from:`这个方法好像是`XRTrace`的。。不知道怎么的可能内存泄漏了？我猜。。

**Comment by DevQiao** [comment]
如何区分哪些指标用的是plugin哪些用的是packages，哪些指标有是legacy的？

**Comment by Qusic** [comment]
`[instrument isKindOfClass:XRLegacyInstrument.class]`

**Comment by mengzhb** [comment]
重新下载了xcode9.2依然不能编译通过，感觉是因为升级MacOS到10.13引起的，这个不知道有没有解

**Comment by DevQiao** [comment]
当前版本在macOS 10.12 和Xcode9.2环境下可以编译通过，但是貌似只能顺利解析出FPS数据

**Comment by Qusic** [comment]
xcode 9.4的time profiler 修复了
