### ISSUE TITLE
在XCode 9.3版本下运行报错，无法创建文件

### ISSUE THREAD

**Issue by wjy254834508** [Qusic/TraceUtility#26]
![cd47bf26d19f7ad64b30efbbd0acfbd7a8b5418b11ddde368a pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/32956379/38626378-f6a592ea-3d9b-11e8-8b56-f4aa86328649.png)
错误如图所示

error中也没有任何具体的错误信息

在老版本中运行正常

**Comment by Qusic** [comment]
新版本xcode用了新的document type，修复了
