### ISSUE TITLE
new core animation fps tool

### ISSUE THREAD

**Issue by eughermann** [Qusic/TraceUtility#29]
Hi there.
Apple is doing a great job un-discovering document formats from people.
In new Instruments 'com.apple.xray.instrument-type.coreanimation' tool was deprecated and replaced with 'com.apple.dt.coreanimation-fps'
New instrument does not contain XRVideoCardRun objects, only base XRRun with metadata.
Introspection didn't give positive results to me. I walked through all available ivars, unpacked NSData buffers, but I don't see where actual numbers are.

Any ideas?

**Comment by Qusic** [comment]
duplicate of #28

**Comment by Qusic** [comment]
fixed in 88ef512f62b0883866a6e673beae32cac841ced6
