### ISSUE TITLE
无法读取Activity Monitor -- Live Processes的数据

### ISSUE THREAD

**Issue by mrx1203** [Qusic/TraceUtility#30]
参照fps的写的，Process History，System CPU Summary等的数据可以读取，但是我要的Live Processes的数据读取不了，XRAnalysisCoreReadCursorNext(cursor)返回NO，无法进入循环体读取数据，麻烦帮忙看一下？ 谢谢！

**Comment by one2zero** [comment]
机灵了

**Comment by one2zero** [comment]
Live Processes的数据应该和其他的不一样，是二维的

**Comment by Qusic** [comment]
应该就是table的，不过`-[XRAnalysisCorePivotArray count]` 返回的居然是0。。有空再看看

**Comment by RadioBear** [comment]
遇到同样问题，困惑中。。。

**Comment by mrx1203** [comment]
@Qusic 大佬，抽个时间帮忙看看呗，我对oc不是很懂

**Comment by lvninety** [comment]
I got same issue, it is not working for live processes.. :(

**Comment by superadison** [comment]
遇到同样的问题，没有头绪。。。

**Comment by jimmyleaf** [comment]
今天用class-dump打印出instrument头文件信息，尝试使用
```
@interface XRAnalysisCoreTableViewController : NSViewController <XRFilteredDataSource, XRSearchTarget>
- (DTRenderableContentResponse *)_currentResponse;
- (void)setDocumentInspectionTime:(unsigned long long)arg1;
@end
```
在display之后加入[controller setDocumentInspectionTime:0];成功获取数据
另外可通过此方法遍历所有数据
```
XRTimeRange timeRange= [run timeRange];
XRTime len = timeRange.length;
int length = floorf(len / 10e8);
for (int i = 0; i <= length; i++){
    [controller setDocumentInspectionTime:(i * 10e8)];
    XRAnalysisCorePivotArray *array = controller._currentResponse.content.rows;
...
}
```

**Comment by mrx1203** [comment]
@jimmyleaf 用你的方法的确可以成功获取数据了，感谢提供方法。Live Processes的数据就像 @one2zero 说的，是个二维的，一个时间点对应了多个进程的数据，需要通过时间点来查询进程数据。

**Comment by yusunan** [comment]
@jimmyleaf 你好，这个setDocumentInspectionTime在Xcode 11上现在不好用了，请问有什么新方法么
