### ISSUE TITLE
 在数据量比较大的时候获取fps数据不全

### ISSUE THREAD

**Issue by LWSSS** [Qusic/TraceUtility#34]
如果在一个instruments中各种数据都有，且数据较大的时候，按照demo里的方法取出来的数据只有很少的一段，这个请问有大神做过研究的嘛？怎么解决呢

**Comment by LWSSS** [comment]
我指的是fps数据

**Comment by Qusic** [comment]
试试`setDocumentInspectionTime`？
https://github.com/Qusic/TraceUtility/issues/30#issuecomment-418110252
