### ISSUE TITLE
How to get TableID in order to get table from core

### ISSUE THREAD

**Issue by Sennialin** [Qusic/TraceUtility#4]
According to your Comments in code : " weightCount can be obtained in this path: core -> table -> projector -> spec -> dependentVariableCount". I dump the headers to find sth useful function. 
In XRAnalysisCore.h， There is  a function "- (XRAnalysisCoreTable*)tableWithID:(unsigned int)tableID" which may be get table from core. However I can't get the tableID. Could you provide some suggestions  to get tableID from core.

**Comment by Qusic** [comment]
I haven't looked into it for enough details to implement the whole process. You may have to work on you own for now. I don't use TraceUtility in my projects and it is not a priority for me to keep it up to date.

**Comment by Sennialin** [comment]
Thank you all the same~
